name: vs_femalefellows
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.6.3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^4.9.2
  cupertino_icons: ^1.0.2
  firebase_core: ^2.20.0
  firebase_auth: ^4.12.0
  firebase_storage: ^11.2.7
  smooth_page_indicator: ^1.1.0
  date_format: ^2.0.7
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_bloc: ^8.0.0
  equatable: ^2.0.5
  bloc: ^8.1.2
  json_annotation: ^4.8.1
  image_picker: ^1.0.4
  geolocator: ^10.1.0
  url_launcher: ^6.2.1
  flutter_svg: ^2.0.9
  language_picker: ^0.4.3
  shared_preferences: ^2.2.2
  geoflutterfire_plus: ^0.0.20
  geocoding: ^2.1.1
  youtube_player_flutter: ^8.1.2
  go_router: ^13.1.0
  custom_sliding_segmented_control: ^1.8.1
  rxdart: ^0.27.7


dev_dependencies:
  #firebase_auth_platform_interface: ^6.15.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/images/femalefellows-app-icon1.png"
  image_path_android: "lib/images/femalefellows-app-icon1.png"
  min_sdk_android: 23
  adaptive_icon_background: "#FCD0DC"
  adaptive_icon_foreground: "lib/images/femalefellows-app-icon.png"

  # after executing dart run flutter_launcher_icons -f pubspec.yaml, override ic_launcher.xml with:
  #<foreground>
  #  <inset
  #    android:drawable="@drawable/ic_launcher_foreground"
  #    android:inset="24%" />
  #</foreground>  


flutter:
  generate: true

  uses-material-design: true

 
  assets:
    - lib/images/
 
  fonts:
  - family: Circular
    fonts:
      - asset: lib/fonts/circular-std-medium-500.ttf

