name: femalefellows
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.5.11

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^5.2.1
  cupertino_icons: ^1.0.8
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  firebase_storage: ^12.1.3
  smooth_page_indicator: ^1.1.0
  date_format: ^2.0.7
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  bloc: ^8.1.4
  json_annotation: ^4.9.0
  image_picker: ^1.1.0
  geolocator: ^12.0.0
  #url_launcher: ^6.3.0
  flutter_svg: ^2.0.10+1
  language_picker: ^0.4.3
  shared_preferences: ^2.2.3
  geoflutterfire_plus: #^0.0.21
    git: https://github.com/Trinistar/geoflutterfire_plus.git
  geocoding: ^3.0.0
  #youtube_player_flutter: ^9.0.3
  go_router: ^14.0.0
  custom_sliding_segmented_control: ^1.8.1
  rxdart: ^0.27.7
  flutter_linkify: ^6.0.0
  html: ^0.15.4
  firebase_messaging: ^15.0.4
  cloud_functions: ^5.0.0
  flutter_local_notifications: ^17.1.2
  firebase_dynamic_links: ^6.0.0
  
dependency_overrides:
  url_launcher:
    git:
      url: https://github.com/hellohuanlin/packages.git
      path: packages/url_launcher/url_launcher
      ref: urllauncher_fix_main_actor_completion_conformance


dev_dependencies:
  #firebase_auth_platform_interface: ^6.15.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.9
  flutter_oss_licenses: ^3.0.2
  
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/images/femalefellows-app-icon1.png"
  image_path_ios: "lib/images/femalefellows-app-icon-1.png"
  remove_alpha_ios: true
  image_path_android: "lib/images/femalefellows-app-icon1.png"
  min_sdk_android: 23
  adaptive_icon_background: "#FCD0DC"
  adaptive_icon_foreground: "lib/images/femalefellows-app-icon.png"

  # after executing dart run flutter_launcher_icons -f pubspec.yaml, override ic_launcher.xml with:
  #<foreground>
  #  <inset
  #    android:drawable="@drawable/ic_launcher_foreground"
  #    android:inset="24%" />
  #</foreground>  


flutter:
  generate: true

  uses-material-design: true

 
  assets:
    - lib/images/
 
  fonts:
  - family: Circular
    fonts:
      - asset: lib/fonts/circular-std-medium-500.ttf

